"""Add task_users many-to-many relationship

Revision ID: 4230682efa7e
Revises: b733ec92cb38
Create Date: 2024-12-18 13:01:30.240472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4230682efa7e'
down_revision: Union[str, None] = 'b733ec92cb38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
